import type { VizEntry } from './viz-catalog';

export const STORY_PROLOGUE_FR = {
  eyebrow: 'Une visite guidée',
  title: 'À quoi ressemble vraiment un tube ?',
  lead: 'Chaque écoute sur Spotify laisse une trace sous forme de données : dansabilité, énergie, tempo, volume sonore et bien plus. Ce tableau de bord transforme ces caractéristiques audio en une histoire : comment les genres diffèrent, ce qui est lié à la popularité et quels profils se dégagent chez les plus grands artistes.',
  bridge: 'Faites défiler les dix chapitres interactifs ou accédez directement à une section via la barre latérale. Survolez les graphiques pour plus de détails et utilisez les filtres lorsque disponibles.',
};

export const VIZ_CATALOG_FR: VizEntry[] = [
  {
    id: 1,
    anchor: 'viz-1',
    title: 'Coordonnées parallèles des genres',
    subtitle: 'Moyennes des caractéristiques audio par famille de genres',
    source: 'viz-1 (Plotly → D3)',
    chapter: 'Chapitre 01 — L’empreinte des genres',
    narrative: 'Dans cette première visualisation, chaque ligne colorée représente une famille de genres qui traverse plusieurs axes correspondant aux caractéristiques audio. Les familles qui montent et descendent ensemble partagent un profil similaire.',
    insight: 'Certains groupes de lignes évoluent en synchronie. On distingue quatre grandes catégories : Classique / Instrumental et Ambient / Chill ; Folk / Acoustic et Jazz / Blues ; Pop, Latin / World et R&B / Soul ; Electronic / Dance, Rock / Metal et Hip-hop / Rap. Cela révèle des proximités sonores inattendues entre genres.',
    readingGuide: 'Survolez une ligne pour afficher ses détails. Activez ou désactivez des familles via la légende pour mieux comparer celles qui vous intéressent.',
  },
  {
    id: 2,
    anchor: 'viz-2',
    title: 'Durée par genre',
    subtitle: 'Distribution des durées selon les familles de genres',
    source: 'viz-2 (Plotly → D3)',
    chapter: 'Chapitre 02 — Quelle est la durée d’une chanson ?',
    narrative: 'La durée d’un morceau est une convention discrète mais importante. Ces boîtes à moustaches montrent la distribution complète des durées pour chaque famille de genres. La ligne pointillée correspond à la médiane de la famille Electronic, utilisée comme référence.',
    insight: 'Parmi les quatre catégories identifiées précédemment, seules deux présentent des durées homogènes : Classique / Instrumental et Ambient / Chill, ainsi que Pop, Latin / World et R&B / Soul. Les genres Electronic et Jazz ont une grande variabilité, tandis que Folk, Rock et Hip-Hop sont plus uniformes.',
    readingGuide: 'Comparez la médiane (ligne centrale) et la dispersion (taille de la boîte). Triez les genres pour identifier les plus courts ou les plus longs.',
  },
  {
    id: 3,
    anchor: 'viz-3',
    title: 'Genres explicites',
    subtitle: 'Barres empilées à 100 %',
    source: 'viz-3',
    chapter: 'Chapitre 03 — Paroles et contenu',
    narrative: 'Ces barres empilées montrent la proportion de morceaux explicites versus non explicites pour chaque famille de genres.',
    insight: 'Les catégories Electronic / Dance, Rock / Metal et Hip-hop / Rap présentent une forte proportion de contenu explicite. R&B / Soul est également élevé, tandis que les genres majoritairement propres sont souvent instrumentaux.',
    readingGuide: 'Survolez les segments pour voir les pourcentages précis. Triez par proportion explicite pour comparer les genres.',
  },
  {
    id: 4,
    anchor: 'viz-4',
    title: 'Corrélation avec la popularité',
    subtitle: 'Corrélation des caractéristiques audio',
    source: 'viz-4',
    chapter: 'Chapitre 04 — Ce que la popularité écoute',
    narrative: 'Ce graphique examine quelles caractéristiques audio sont associées à la popularité Spotify. Chaque barre représente la corrélation entre une caractéristique et le score de popularité.',
    insight: 'Les caractéristiques positives indiquent qu’elles augmentent avec la popularité. Le volume sonore (loudness) et la dansabilité sont les plus corrélés positivement, tandis que l’instrumentalité et la parole (speechiness) sont négativement corrélées.',
    readingGuide: 'Comparez les vues Pearson et Spearman pour identifier les relations les plus robustes.',
  },
  {
    id: 5,
    anchor: 'viz-5',
    title: 'Tempo vs dansabilité',
    subtitle: 'Nuage de points par genre',
    source: 'viz-5',
    chapter: 'Chapitre 05 — L’équation du rythme',
    narrative: 'Le tempo définit la vitesse d’un morceau, tandis que la dansabilité mesure sa facilité à être dansé. Chaque graphique représente un genre avec une tendance locale.',
    insight: 'De manière surprenante, un tempo plus élevé est souvent associé à une dansabilité plus faible. Seuls les genres Classique et Jazz montrent l’effet inverse.',
    readingGuide: 'Activez ou désactivez des genres. Une pente forte indique une relation marquée entre tempo et dansabilité.',
  },
  {
    id: 6,
    anchor: 'viz-6',
    title: 'Acousticité vs popularité',
    subtitle: 'Comparaison Pop vs Rock',
    source: 'viz-6',
    chapter: 'Chapitre 06 — L’impact de l’acoustique',
    narrative: 'L’acousticité mesure le caractère « acoustique » d’un morceau. Cette visualisation compare Pop et Rock pour analyser son lien avec la popularité.',
    insight: 'La relation est globalement faible. Cependant, Pop et Rock montrent des tendances opposées : jusqu’à un certain seuil, plus d’acousticité favorise la popularité en Pop, mais la réduit en Rock. La tendance s’inverse dans les valeurs les plus élevées.',
    readingGuide: 'Une pente ascendante indique un effet positif de l’acousticité sur la popularité.',
  },
  {
    id: 7,
    anchor: 'viz-7',
    title: 'Durée vs popularité',
    subtitle: 'Popularité moyenne par tranches de 30 secondes',
    source: 'viz-7',
    chapter: 'Chapitre 07 — La durée idéale',
    narrative: 'Les morceaux sont regroupés en intervalles de 30 secondes pour analyser leur popularité moyenne.',
    insight: 'Les morceaux entre 3 et 5 minutes sont les plus populaires. Les titres très courts chutent fortement, tandis que les morceaux très longs conservent une popularité étonnamment élevée.',
    readingGuide: 'Survolez une barre pour voir les valeurs exactes. La ligne pointillée représente la moyenne globale.',
  },
  {
    id: 8,
    anchor: 'viz-8',
    title: 'Composition de la popularité',
    subtitle: 'Répartition par paliers de popularité',
    source: 'viz-8 (Plotly → D3)',
    chapter: 'Chapitre 08 — Les paliers de succès',
    narrative: 'Les morceaux sont divisés en cinq niveaux de popularité, chacun décomposé selon une caractéristique audio.',
    insight: 'Les morceaux les plus populaires présentent moins de valence négative, une forte dansabilité et plus d’énergie. Ils sont aussi davantage vocaux. Aucun lien clair n’apparaît avec la speechiness.',
    readingGuide: 'Sélectionnez une caractéristique pour voir comment elle varie selon les niveaux de popularité.',
  },
  {
    id: 9,
    anchor: 'viz-9',
    title: 'Cartes de densité',
    subtitle: 'Densité des caractéristiques audio',
    source: 'viz-9 (Plotly → D3)',
    chapter: 'Chapitre 09 —  Où se rassemble la foule',
    narrative: 'Les cartes de densité montrent où les morceaux se concentrent dans l’espace des caractéristiques audio.',
    insight: 'L’énergie et le volume sonore évoluent ensemble. La relation entre speechiness et dansabilité est faible, mais les morceaux les plus fréquents ont une faible speechiness.',
    readingGuide: 'Alternez entre les vues pour explorer différentes relations entre caractéristiques.',
  },
  {
    id: 10,
    anchor: 'viz-10',
    title: 'Profils des artistes',
    subtitle: 'Profils radar des 12 artistes les plus populaires',
    source: 'viz-10',
    chapter: 'Chapitre 10 — Des visages dans les données',
    narrative: 'Cette visualisation met en avant les artistes via des graphiques radar représentant leur profil audio moyen.',
    insight: 'Certains profils se chevauchent fortement, notamment avec un volume et un tempo élevés. L’acousticité et la durée sont généralement faibles. Cependant, des différences importantes apparaissent en dansabilité, énergie et valence.',
    readingGuide: 'Survolez pour voir les valeurs. Cliquez pour comparer plusieurs artistes simultanément.',
  },
];
