import type { VizEntry } from './viz-catalog';

export const STORY_PROLOGUE_FR = {
  eyebrow: 'Une visite guidée',
  title: 'À quoi ressemble vraiment un tube ?',
  lead: 'Chaque écoute sur Spotify laisse une trace numérique — dansabilité, énergie, tempo, volume sonore et plus encore. Ce tableau de bord transforme ces caractéristiques audio en récit : comment les genres diffèrent, ce qui corrèle avec la popularité, et où se placent les plus grands artistes.',
  bridge: 'Faites défiler dix chapitres interactifs ou sautez à n\'importe quelle section depuis la barre latérale. Survolez les graphiques pour les détails, utilisez les filtres quand ils sont disponibles, et suivez le fil du grand tableau jusqu\'aux artistes individuels.',
};

export const VIZ_CATALOG_FR: VizEntry[] = [
  {
    id: 1,
    anchor: 'viz-1',
    title: 'Coordonnées parallèles',
    subtitle: 'Moyennes des caractéristiques audio par genre',
    source: 'viz-1 (Plotly → D3)',
    chapter: 'Chapitre 01 — L\'empreinte du genre',
    narrative: 'Avant de comparer des titres individuels, il nous faut une carte du monde musical. Chaque ligne de ce graphique en coordonnées parallèles est un genre — dansabilité, énergie, acousticité, valence et popularité reliées sur cinq axes. Les genres qui montent et descendent ensemble partagent une personnalité sonore. Les zigzags marqués révèlent ce qui rend chaque genre unique.',
    insight: 'Cherchez des grappes de lignes qui évoluent en synchronie. C\'est la preuve de genres qui sonnent pareil dans les données, même quand leurs noms semblent éloignés.',
    readingGuide: 'Suivez une ligne colorée sur tous les axes. Comparez comment pop, rock et électronique échangent énergie et acousticité.',
  },
  {
    id: 2,
    anchor: 'viz-2',
    title: 'Boîtes à moustaches de durée',
    subtitle: 'Normes de durée des titres par genre',
    source: 'viz-2 (Plotly → D3)',
    chapter: 'Chapitre 02 — Quelle est la longueur d\'une chanson ?',
    narrative: 'La durée est l\'une des conventions les plus discrètes de la musique — les auditeurs la remarquent rarement, mais les producteurs en ressentent la pression. Ces boîtes à moustaches montrent la durée des titres dans chacun des 50 genres principaux, des singles courts aux morceaux d\'album plus longs. La ligne de référence pointillée marque la médiane de la pop, notre base pour un titre typique.',
    insight: 'Des boîtes larges montrent qu\'un genre accepte de nombreuses durées. Des boîtes étroites indiquent que les artistes ont convergé vers une formule standard.',
    readingGuide: 'Comparez la médiane (ligne centrale) et l\'étalement (hauteur de la boîte) de chaque genre à la référence pop. Quels genres dépassent régulièrement la durée d\'un tube standard ?',
  },
  {
    id: 3,
    anchor: 'viz-3',
    title: 'Explicite vs propre',
    subtitle: 'Barres empilées à 100 % par genre',
    source: 'viz-3',
    chapter: 'Chapitre 03 — Paroles, étiquettes et limites',
    narrative: 'Le contenu explicite n\'est pas qu\'un autocollant parental — c\'est une caractéristique structurelle de la façon dont les genres se présentent. Ces barres empilées montrent, pour chaque genre, la part de titres marqués explicites ou propres. Cette répartition reflète la culture, le public et les normes des plateformes autant que le choix des artistes.',
    insight: 'Les genres dominés par une seule couleur vous renseignent sur leur public et leur stratégie de sortie, pas seulement sur leur vocabulaire.',
    readingGuide: 'Lisez chaque barre comme une proportion sur 100. Survolez pour voir les pourcentages exacts et repérez les genres fortement explicites.',
  },
  {
    id: 4,
    anchor: 'viz-4',
    title: 'Corrélation des caractéristiques',
    subtitle: 'Pearson / Spearman vs popularité',
    source: 'viz-4',
    chapter: 'Chapitre 04 — Ce que la popularité écoute',
    narrative: 'Ici, nous posons la question centrale du jeu de données : quelles qualités mesurables accompagnent la popularité Spotify ? Chaque barre est une caractéristique audio — dansabilité, énergie, speechiness et plus — évaluée selon sa corrélation avec le score de popularité. Basculez entre Pearson (linéaire) et Spearman (par rangs) pour voir si les relations tiennent sous d\'autres hypothèses.',
    insight: 'Une barre positive signifie que davantage de cette caractéristique tend à se traduire par plus de popularité. La force compte autant que la direction — les corrélations faibles façonnent quand même le tube moyen.',
    readingGuide: 'Commencez avec Pearson, puis passez à Spearman. Les caractéristiques importantes dans les deux vues sont les signaux les plus fiables.',
  },
  {
    id: 5,
    anchor: 'viz-5',
    title: 'Tempo vs dansabilité',
    subtitle: 'Nuage de points facetté par genre',
    source: 'viz-5',
    chapter: 'Chapitre 05 — L\'équation de la piste de danse',
    narrative: 'Le tempo donne la cadence et la dansabilité capte à quel point il est facile de bouger sur un morceau. Ensemble, ils décrivent la physique du groove. Ces nuages facettés échantillonnent des titres de grands genres, chaque panneau avec son nuage de points et une droite de régression montrant la tendance locale. Filtrez les genres, ajustez la taille de l\'échantillon ou cherchez un artiste pour voir où il se situe.',
    insight: 'Une pente ascendante marquée signifie que, dans ce genre, les morceaux plus rapides tendent aussi à paraître plus dansables. Toutes les règles ne s\'appliquent pas partout.',
    readingGuide: 'Choisissez deux genres et comparez leurs droites de régression. Utilisez la recherche pour repérer un artiste favori dans le nuage.',
  },
  {
    id: 6,
    anchor: 'viz-6',
    title: 'Acousticité vs popularité',
    subtitle: 'Comparaison Pop vs Rock',
    source: 'viz-6',
    chapter: 'Chapitre 06 — Acoustique contre amplifié',
    narrative: 'L\'acousticité mesure à quel point un enregistrement sonne débranché — guitares claires et ambiance de salle scorent haut, tandis qu\'une production dense score bas. Ce chapitre oppose Pop et Rock en comparaison directe, avec droites de régression et moyennes par tranches montrant si les sons plus organiques aident ou nuisent à la popularité dans chaque camp.',
    insight: 'Si les pentes diffèrent entre Pop et Rock, le même choix sonore ne porte pas la même signification selon le genre.',
    readingGuide: 'Lisez les cartes statistiques pour r de Pearson et la popularité moyenne des titres peu ou très acoustiques, puis confirmez le motif dans le nuage.',
  },
  {
    id: 7,
    anchor: 'viz-7',
    title: 'Durée vs popularité',
    subtitle: 'Tendances par tranches de durée',
    source: 'viz-7',
    chapter: 'Chapitre 07 — La zone idéale',
    narrative: 'Formats radio, attention des playlists et taux de skip en streaming posent tous la même question : existe-t-il une durée idéale ? Les titres sont regroupés par tranches de 30 secondes et la hauteur de chaque barre correspond à la popularité moyenne dans cet intervalle. Faites défiler vers la bande de trois à cinq minutes où les tubes se concentrent souvent.',
    insight: 'La réponse principale se met à jour en direct — observez comment la zone idéale change quand vous modifiez l\'intervalle visible.',
    readingGuide: 'Survolez les barres pour les moyennes exactes, basculez les décomptes de titres pour la taille d\'échantillon, et explorez la bande 3 à 5 min.',
  },
  {
    id: 8,
    anchor: 'viz-8',
    title: 'Composition de popularité',
    subtitle: 'Barres empilées par palier de popularité',
    source: 'viz-8 (Plotly → D3)',
    chapter: 'Chapitre 08 — Paliers de succès',
    narrative: 'Tous les titres populaires ne le sont pas de la même façon. Les genres sont divisés en paliers de popularité — des titres émergents aux dominants des charts — puis décomposés selon une caractéristique audio de votre choix. Le résultat est un portrait empilé de ce que chaque palier sonne dans un genre. Les tubes ont-ils plus d\'énergie que les favoris du catalogue long-tail ?',
    insight: 'Changez de caractéristique pour voir si le succès à différents paliers repose sur la dansabilité, la valence, l\'acousticité ou autre chose.',
    readingGuide: 'Choisissez une caractéristique, puis lisez chaque pile de gauche à droite comme des paliers de popularité croissante dans un genre.',
  },
  {
    id: 9,
    anchor: 'viz-9',
    title: 'Cartes de densité',
    subtitle: 'Cartes de chaleur 2D des caractéristiques',
    source: 'viz-9 (Plotly → D3)',
    chapter: 'Chapitre 09 — Où se rassemble la foule',
    narrative: 'Les nuages de points montrent des données individuelles, tandis que les cartes de chaleur révèlent la concentration. Ces grilles de densité 50x50 révèlent où les titres s\'accumulent dans l\'espace des caractéristiques — les cellules vives sont le terrain commun sonore, les coins sombres des combinaisons rares. Les histogrammes marginaux montrent les distributions sous-jacentes. Basculez entre Énergie/Volume et Parole/Dansabilité pour explorer deux cartes du catalogue.',
    insight: 'Les zones chaudes représentent le son typique du jeu de données. Les zones froides correspondent aux combinaisons rares et aux expérimentations.',
    readingGuide: 'Changez de mode et cherchez des bandes diagonales chaudes — elles signalent des caractéristiques qui montent et descendent ensemble sur des milliers de titres.',
  },
  {
    id: 10,
    anchor: 'viz-10',
    title: 'Tableau de bord artiste',
    subtitle: 'Profils radar et courbes de tendance',
    source: 'viz-10',
    chapter: 'Chapitre 10 — Des visages dans les données',
    narrative: 'Nous terminons en zoomant des genres vers les noms. Les douze meilleurs interprètes ont chacun un profil radar — une forme résumant leur caractère audio moyen — et un panneau de tendance suivant une métrique choisie à travers leur discographie ordonnée par popularité. Sélectionnez des artistes, changez de métrique et comparez les signatures côte à côte.',
    insight: 'Des formes radar qui se chevauchent désignent des artistes aux identités sonores semblables. Des formes divergentes révèlent pourquoi deux stars tout aussi populaires peuvent paraître si différentes l\'une de l\'autre.',
    readingGuide: 'Cochez trois artistes sur le radar, puis changez la métrique de tendance pour voir si leur succès suit la durée, l\'énergie ou un autre fil.',
  },
];
