import type { VizEntry } from './viz-catalog';

export const STORY_PROLOGUE_FR = {
  eyebrow: 'Une visite guidée',
  title: 'À quoi ressemble vraiment un tube ?',
  lead: 'Chaque écoute sur Spotify laisse une trace numérique — dansabilité, énergie, tempo, volume sonore et plus encore. Ce tableau de bord transforme ces caractéristiques audio en récit : comment les genres diffèrent, ce qui corrèle avec la popularité, et où se placent les plus grands artistes.',
  bridge: 'Faites défiler dix chapitres interactifs ou sautez à n\'importe quelle section depuis la barre latérale. Survolez les graphiques pour les détails, utilisez les filtres quand ils sont disponibles, et suivez le fil du grand tableau jusqu\'aux artistes individuels.',
};

export const VIZ_CATALOG_FR: VizEntry[] = [
  {
    id: 1,
    anchor: 'viz-1',
    title: 'Coordonnées parallèles',
    subtitle: 'Moyennes des caractéristiques audio par famille de genres',
    source: 'viz-1 (Plotly → D3)',
    chapter: 'Chapitre 01 — L\'empreinte du genre',
    narrative: 'Avant de comparer des titres individuels, il nous faut une carte du monde musical. Chaque ligne colorée représente une famille de genres — sa dansabilité, son énergie, son acousticité, sa valence, son tempo et plus encore, reliés sur plusieurs axes. Les familles qui montent et descendent ensemble partagent une personnalité sonore commune. Les zigzags prononcés révèlent ce qui rend chaque famille distincte.',
    insight: 'Repérez les groupes de lignes qui évoluent en synchronie — c\'est la preuve que ces familles sonnent de manière similaire dans les données, même si leurs noms semblent sans rapport.',
    readingGuide: 'Suivez une ligne colorée de gauche à droite sur tous les axes. Activez ou désactivez des familles via les cases de la légende pour isoler celles que vous souhaitez comparer.',
  },
  {
    id: 2,
    anchor: 'viz-2',
    title: 'Boîtes à moustaches de durée',
    subtitle: 'Distribution des durées par famille de genres',
    source: 'viz-2 (Plotly → D3)',
    chapter: 'Chapitre 02 — Quelle est la longueur d\'une chanson ?',
    narrative: 'La durée est l\'une des conventions les plus discrètes de la musique — les auditeurs la remarquent rarement, mais les producteurs en ressentent la pression. Ces boîtes à moustaches montrent la distribution complète des durées sur dix familles de genres, des singles radio courts aux morceaux d\'album plus longs. La ligne de référence pointillée marque la médiane de la famille Pop comme base de comparaison.',
    insight: 'Une boîte large indique qu\'une famille de genres tolère de nombreuses durées différentes. Une boîte étroite suggère que les artistes ont convergé vers un format clairement établi.',
    readingGuide: 'Comparez la médiane (trait central) et l\'étalement (hauteur de la boîte) de chaque famille par rapport à la ligne de référence Pop. Triez par ordre croissant ou décroissant pour trouver les genres les plus courts et les plus longs.',
  },
  {
    id: 3,
    anchor: 'viz-3',
    title: 'Explicite vs propre',
    subtitle: 'Barres empilées à 100 % par famille de genres',
    source: 'viz-3',
    chapter: 'Chapitre 03 — Paroles, étiquettes et limites',
    narrative: 'La mention de contenu explicite n\'est pas qu\'un avertissement parental — elle reflète la façon dont un genre se présente à son public. Ces barres empilées à 100 % montrent la proportion de titres explicites et propres pour chaque famille de genres. Cette répartition révèle des normes culturelles, des profils d\'audience et des stratégies de positionnement sur les plateformes, autant que des choix artistiques individuels.',
    insight: 'Une famille dominée par une seule couleur affiche une identité culturelle forte autour de son contenu. Les genres presque entièrement propres sont souvent instrumentaux, internationaux ou destinés à un jeune public.',
    readingGuide: 'Lisez chaque barre comme une proportion dont la somme est 100 %. Survolez un segment pour voir le pourcentage exact. Triez par taux de contenu explicite pour classer les familles du plus au moins explicite.',
  },
  {
    id: 4,
    anchor: 'viz-4',
    title: 'Corrélation des caractéristiques',
    subtitle: 'Pearson / Spearman vs popularité',
    source: 'viz-4',
    chapter: 'Chapitre 04 — Ce que la popularité écoute',
    narrative: 'Ce graphique pose la question centrale du jeu de données : quelles qualités audio accompagnent la popularité Spotify ? Chaque barre représente une caractéristique — dansabilité, énergie, volume, parole et plus — évaluée selon la force de sa corrélation avec le score de popularité. Basculez entre Pearson (relation linéaire) et Spearman (basé sur les rangs) pour tester la robustesse de chaque tendance.',
    insight: 'Une barre positive signifie que davantage de cette caractéristique accompagne généralement une popularité plus élevée. Les caractéristiques qui restent fortes en Pearson et en Spearman sont les plus fiables.',
    readingGuide: 'Commencez avec Pearson pour voir la direction générale, puis passez à Spearman. Les caractéristiques qui maintiennent leur position dans les deux vues sont les signaux les plus solides.',
  },
  {
    id: 5,
    anchor: 'viz-5',
    title: 'Tempo vs dansabilité',
    subtitle: 'Nuage de points facetté par genre',
    source: 'viz-5',
    chapter: 'Chapitre 05 — L\'équation de la piste de danse',
    narrative: 'Le tempo fixe la cadence et la dansabilité mesure à quel point il est facile de bouger sur un morceau. Ensemble, ils décrivent la physique du groove. Chaque panneau de ce graphique facetté se concentre sur un genre, avec un échantillon de titres et une droite de régression qui trace la tendance locale. Activez ou désactivez des panneaux via les puces de genre pour affiner votre analyse.',
    insight: 'Une pente ascendante prononcée indique que, dans ce genre, les titres plus rapides tendent aussi à être plus dansables. Cette relation ne se vérifie pas de la même façon dans tous les genres.',
    readingGuide: 'Comparez les droites de régression entre les panneaux — une pente marquée signifie que tempo et dansabilité sont étroitement liés dans ce genre. Utilisez les puces pour sélectionner les genres que vous souhaitez étudier.',
  },
  {
    id: 6,
    anchor: 'viz-6',
    title: 'Acousticité vs popularité',
    subtitle: 'Comparaison Pop vs Rock',
    source: 'viz-6',
    chapter: 'Chapitre 06 — Acoustique contre amplifié',
    narrative: 'L\'acousticité mesure à quel point un enregistrement sonne « débranché » — guitares claires et ambiance naturelle scorent haut, tandis qu\'une production électronique dense score bas. Ce chapitre oppose directement Pop et Rock, avec une droite de régression et une courbe de moyenne par tranches, pour voir si un son plus organique aide ou pénalise la popularité dans chacun de ces genres.',
    insight: 'Si les pentes diffèrent nettement entre Pop et Rock, cela signifie que le même choix sonore ne produit pas le même effet selon le genre dans lequel il est utilisé.',
    readingGuide: 'Observez la droite de régression pointillée et la courbe de moyenne pleine dans chaque panneau. Une pente ascendante indique que les titres plus acoustiques sont en moyenne plus populaires dans ce genre.',
  },
  {
    id: 7,
    anchor: 'viz-7',
    title: 'Durée vs popularité',
    subtitle: 'Popularité moyenne par tranches de 30 secondes',
    source: 'viz-7',
    chapter: 'Chapitre 07 — La zone idéale',
    narrative: 'Formats radio, attention des playlists et taux de skip en streaming posent tous la même question : existe-t-il une durée idéale pour un titre ? Les morceaux sont regroupés par tranches de 30 secondes et chaque barre indique la popularité moyenne dans cet intervalle. Faites défiler vers la bande de trois à cinq minutes pour voir où les tubes se concentrent.',
    insight: 'La popularité ne croît pas de façon continue avec la durée. Il existe une zone de pointe bien délimitée — les titres en dehors, qu\'ils soient trop courts ou trop longs, tendent à scorer moins haut en moyenne.',
    readingGuide: 'Survolez une barre pour voir la popularité moyenne exacte et le nombre de titres dans cet intervalle. La ligne pointillée horizontale marque la moyenne globale du jeu de données.',
  },
  {
    id: 8,
    anchor: 'viz-8',
    title: 'Composition de popularité',
    subtitle: 'Barres empilées par palier de popularité',
    source: 'viz-8 (Plotly → D3)',
    chapter: 'Chapitre 08 — Paliers de succès',
    narrative: 'Tous les titres populaires ne le sont pas de la même manière. Les titres sont répartis en cinq paliers de popularité — des plus discrets aux dominants des classements — puis chaque palier est décomposé selon une caractéristique audio de votre choix. Les barres empilées révèlent ce que chaque palier sonne vraiment. Les plus grands hits ont-ils plus d\'énergie ? Sont-ils plus dansables ? La réponse change selon la caractéristique sélectionnée.',
    insight: 'Changez de caractéristique pour observer si la composition évolue selon les paliers. Une caractéristique uniformément répartie est moins prédictive du succès que celle qui se concentre au sommet.',
    readingGuide: 'Sélectionnez une caractéristique via les boutons en haut. Lisez ensuite les barres de gauche à droite — chaque colonne est un palier de popularité, et la nuance indique la proportion tombant dans chaque catégorie.',
  },
  {
    id: 9,
    anchor: 'viz-9',
    title: 'Cartes de densité',
    subtitle: 'Cartes de chaleur 2D des caractéristiques',
    source: 'viz-9 (Plotly → D3)',
    chapter: 'Chapitre 09 — Où se rassemble la foule',
    narrative: 'Là où les nuages de points montrent des titres individuels, les cartes de densité révèlent où ils se concentrent. Ces grilles 50×50 indiquent quelles combinaisons de deux caractéristiques audio sont les plus fréquentes dans le catalogue. Les cellules vives représentent le courant sonore dominant ; les zones sombres correspondent aux combinaisons rares. Les histogrammes sur chaque bord montrent les distributions individuelles. Basculez entre Énergie/Volume et Parole/Dansabilité pour explorer deux vues distinctes du jeu de données.',
    insight: 'Les cellules les plus lumineuses définissent le titre Spotify typique. Les zones plus sombres abritent des combinaisons inhabituelles — expérimentations de genres ou styles de niche.',
    readingGuide: 'Changez de mode avec les boutons. Cherchez des bandes diagonales de haute densité — elles révèlent des caractéristiques qui augmentent ou diminuent ensemble.',
  },
  {
    id: 10,
    anchor: 'viz-10',
    title: 'Tableau de bord artiste',
    subtitle: 'Profils radar des 12 meilleurs interprètes',
    source: 'viz-10',
    chapter: 'Chapitre 10 — Des visages dans les données',
    narrative: 'Nous terminons en zoomant des genres vers les artistes. Les douze meilleurs interprètes sont présentés sous forme d\'une grille de petits graphiques radar — chacun un polygone résumant le profil audio moyen de l\'artiste sur huit dimensions. Cliquez sur une carte pour ajouter ou retirer cet artiste du grand radar de comparaison en bas, où leurs profils se superposent pour une comparaison directe.',
    insight: 'Des formes radar qui se chevauchent désignent des artistes aux identités sonores similaires, même s\'ils appartiennent à des genres différents. Des formes très distinctes expliquent pourquoi deux stars tout aussi populaires peuvent sonner complètement différemment.',
    readingGuide: 'Survolez une petite carte pour voir les valeurs exactes. Cliquez sur les cartes pour activer ou désactiver des artistes dans le grand radar. Commencez avec trois artistes et ajoutez-en un à la fois pour mieux comprendre ce qui change.',
  },
];
